// Generated by gencpp from file fobo/Direction.msg
// DO NOT EDIT!


#ifndef FOBO_MESSAGE_DIRECTION_H
#define FOBO_MESSAGE_DIRECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fobo
{
template <class ContainerAllocator>
struct Direction_
{
  typedef Direction_<ContainerAllocator> Type;

  Direction_()
    : x(0)
    , z(0)  {
    }
  Direction_(const ContainerAllocator& _alloc)
    : x(0)
    , z(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::fobo::Direction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fobo::Direction_<ContainerAllocator> const> ConstPtr;

}; // struct Direction_

typedef ::fobo::Direction_<std::allocator<void> > Direction;

typedef boost::shared_ptr< ::fobo::Direction > DirectionPtr;
typedef boost::shared_ptr< ::fobo::Direction const> DirectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fobo::Direction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fobo::Direction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fobo::Direction_<ContainerAllocator1> & lhs, const ::fobo::Direction_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fobo::Direction_<ContainerAllocator1> & lhs, const ::fobo::Direction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fobo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fobo::Direction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fobo::Direction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fobo::Direction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fobo::Direction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fobo::Direction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fobo::Direction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fobo::Direction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eee2fa0953539393a39986ddd18480b3";
  }

  static const char* value(const ::fobo::Direction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeee2fa0953539393ULL;
  static const uint64_t static_value2 = 0xa39986ddd18480b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::fobo::Direction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fobo/Direction";
  }

  static const char* value(const ::fobo::Direction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fobo::Direction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 z\n"
;
  }

  static const char* value(const ::fobo::Direction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fobo::Direction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Direction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fobo::Direction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fobo::Direction_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOBO_MESSAGE_DIRECTION_H
