// Generated by gencpp from file led/led.msg
// DO NOT EDIT!


#ifndef LED_MESSAGE_LED_H
#define LED_MESSAGE_LED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace led
{
template <class ContainerAllocator>
struct led_
{
  typedef led_<ContainerAllocator> Type;

  led_()
    : status(false)  {
    }
  led_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::led::led_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::led::led_<ContainerAllocator> const> ConstPtr;

}; // struct led_

typedef ::led::led_<std::allocator<void> > led;

typedef boost::shared_ptr< ::led::led > ledPtr;
typedef boost::shared_ptr< ::led::led const> ledConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::led::led_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::led::led_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::led::led_<ContainerAllocator1> & lhs, const ::led::led_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::led::led_<ContainerAllocator1> & lhs, const ::led::led_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace led

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::led::led_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::led::led_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::led::led_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::led::led_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::led::led_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::led::led_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::led::led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::led::led_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::led::led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "led/led";
  }

  static const char* value(const ::led::led_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::led::led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
;
  }

  static const char* value(const ::led::led_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::led::led_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct led_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::led::led_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::led::led_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LED_MESSAGE_LED_H
